name: pr

on: pull_request

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # pin@v3.0
        with:
          go-version: "1.19"

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@c675eb70db3aa26b496bc4e64da320480338d41b # pin#v3
        with:
          version: v1.51.2

  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # pin@v3.0
        with:
          go-version: "1.19"

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...
